# syntax=docker/dockerfile:1

# We use the normal deployment as it's quite small and quick to build
FROM python:3.7
RUN pip install --upgrade pip==20.2.4

# Copy the requirements and install
WORKDIR /install
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY setup.py setup.py
COPY README.md README.md
RUN mkdir operations
ADD operations /install/ExampleIngest
RUN pip3 install .

# Copy the app and run
WORKDIR /app
COPY run.py run.py
CMD [ "python", "run.py"]
